import { metricCatalog, summarizeMetrics } from './metrics.js';
import { getScenarioManifest } from './scenarios.js';

function renderList(values) {
  return values.map((value) => `- ${value}`).join('\n');
}

export function renderReport() {
  const scenarios = getScenarioManifest();
  const lines = [];

  lines.push('# OpenClaw MiMo Performance Report');
  lines.push('');
  lines.push('This report is a repository-level summary generated by the benchmark scaffold.');
  lines.push('');
  lines.push(`- Scenario count: ${scenarios.length}`);
  lines.push(`- Metric count: ${metricCatalog.length}`);
  lines.push('');
  lines.push('## Scenario matrix');

  for (const scenario of scenarios) {
    lines.push('');
    lines.push(`### ${scenario.name}`);
    lines.push(`- id: ${scenario.id}`);
    lines.push(`- provider: ${scenario.provider}`);
    lines.push(`- focus: ${scenario.focus}`);
    lines.push(`- objective: ${scenario.objective}`);
    lines.push(`- measurements: ${scenario.measurements.join(', ')}`);
  }

  lines.push('');
  lines.push('## Metric catalog');
  lines.push('');
  lines.push(renderList(metricCatalog.map((metric) => `${metric.id} - ${metric.note}`)));
  lines.push('');
  lines.push('## Compact summary');
  lines.push('');
  lines.push(summarizeMetrics());

  return lines.join('\n');
}

export function buildManifest() {
  return {
    project: 'openclaw-mimo-performance-agent',
    description: 'Benchmark and optimization harness for OpenClaw MiMo regressions.',
    scenarios: getScenarioManifest(),
    metrics: metricCatalog
  };
}